# Tensors in torch

In [4]:
Author = "Tabish Showkat"

In [5]:
import torch as tt

creating tensor manually

In [6]:
tensor_manually = tt.tensor([1,2,3])

In [7]:

#identifying shape
tensor_manually.shape #3 columns 1 row

torch.Size([3])

In [8]:
#identifying datatype
print(type(tensor_manually))#class 'torch.Tensor'>

<class 'torch.Tensor'>


In [9]:
#idenfiying datatype
tensor_manually.dtype #integer 64

torch.int64

creating tensor with random

In [10]:
random_tensor = tt.rand(2,3)
print(random_tensor) #prints
#identifying shape it must be 2 rows ,3 columns
print(random_tensor.shape)
#identifying dtype it must be float
print(random_tensor.dtype)
#finding type
print(type(random_tensor)) #it must be < class  torch.tensor >


tensor([[0.5393, 0.3188, 0.7355],
        [0.0764, 0.4837, 0.0478]])
torch.Size([2, 3])
torch.float32
<class 'torch.Tensor'>


In [11]:
#using limits while using randint
tt.randint(size = (2,3),low=1,high = 100)

tensor([[87, 64, 69],
        [58, 57, 31]])

zeros and ones

In [12]:
#using zeros

shape_of_tensor = (2,3)
a=tt.zeros(shape_of_tensor)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
#using ones
shape_of_tensor = (2,3)
a=tt.ones(shape_of_tensor)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

using empty which allocates in cpu and findes the empty space and writes the number of allocation in tensor

In [14]:
shape = (7,7)
tt.empty(shape)

tensor([[-1.1182e-19,  1.6381e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

 basic operations in tensors

In [15]:
tt.manual_seed(100)
a = tt.randint(size=(2,3),low = 5,high=25,dtype=tt.int64)
a

tensor([[ 5, 17, 20],
        [24, 20, 16]])

In [16]:
a+5#element vise adding (scalar+matrix) 

tensor([[10, 22, 25],
        [29, 25, 21]])

In [17]:
#element vise subtracting
a-5

tensor([[ 0, 12, 15],
        [19, 15, 11]])

In [18]:
#multipulcation element vise
a*5

tensor([[ 25,  85, 100],
        [120, 100,  80]])

In [19]:
#division element vis
a/5

tensor([[1.0000, 3.4000, 4.0000],
        [4.8000, 4.0000, 3.2000]])

In [20]:
#power element vise
a**5

tensor([[   3125, 1419857, 3200000],
        [7962624, 3200000, 1048576]])

In [21]:
#sqrt element vise
tt.sqrt(a)

tensor([[2.2361, 4.1231, 4.4721],
        [4.8990, 4.4721, 4.0000]])

### advance operations in tensors
##### -matrix multipulcation 
##### -matrix addition
##### -matrix subtraction
##### -matrix divison
##### -dot product
##### -inverse
##### -transpose
##### -absolute value

In [22]:
m1 = tt.tensor([[1,2,3],
                [4,5,6]])
m1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
print(m1.shape)
print(m1.size)
print(type(m1))
print(m1.dtype)

torch.Size([2, 3])
<built-in method size of Tensor object at 0x0000013005D5B570>
<class 'torch.Tensor'>
torch.int64


In [24]:
m2 = tt.tensor([[2,3],
                [4,5],
                [6,7]])
m2

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [25]:
print("matrix 1:\n",m1)
print("matrix 2:\n",m2)

matrix 1:
 tensor([[1, 2, 3],
        [4, 5, 6]])
matrix 2:
 tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [26]:
print(m1.shape)
print(m2.shape)

torch.Size([2, 3])
torch.Size([3, 2])


In [27]:
tt.matmul(m1,m2) #matrix multipulcation 

tensor([[28, 34],
        [64, 79]])

In [28]:
m1 = tt.randint(size=(2,3),low=5,high=70)
m2 = m1.clone()
print(m2)
print(m1)
print(m1+m2)
print(m1*2)

tensor([[47, 68, 38],
        [30, 19, 63]])
tensor([[47, 68, 38],
        [30, 19, 63]])
tensor([[ 94, 136,  76],
        [ 60,  38, 126]])
tensor([[ 94, 136,  76],
        [ 60,  38, 126]])


In [29]:
#matrix subtraction is same
m1-m2

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
#matrix multipulcation
m1*m2

tensor([[2209, 4624, 1444],
        [ 900,  361, 3969]])

In [31]:
#matrix division
(m1/m2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
print(m1[0])
print(m2[0])
tt.dot(m1[0],m2[0]) #33*33+6*6+30*30 = 2025

tensor([47, 68, 38])
tensor([47, 68, 38])


tensor(8277)

In [33]:
#negative values
a = tt.tensor([1,2,3])
c= tt.neg(a)
c

tensor([-1, -2, -3])

In [34]:
#positive values (abs)
c
tt.abs(c)

tensor([1, 2, 3])

In [35]:
m1

tensor([[47, 68, 38],
        [30, 19, 63]])

In [36]:
tt.transpose(m1,dim1 = 0,dim0=1)


tensor([[47, 30],
        [68, 19],
        [38, 63]])

In [37]:
m10 = tt.randint(size=(2,2),high = 200,low = 5,dtype=tt.float64)
m10

tensor([[ 13.,  73.],
        [164., 129.]], dtype=torch.float64)

In [38]:
tt.inverse(m10)

tensor([[-0.0125,  0.0071],
        [ 0.0159, -0.0013]], dtype=torch.float64)

In [39]:
#copy function clone
a = tt.tensor([1,2,3])
a

tensor([1, 2, 3])

In [40]:
b = tt.clone(a)
b

tensor([1, 2, 3])

In [41]:
a += 5 
a

tensor([6, 7, 8])

In [42]:
b

tensor([1, 2, 3])

in place function

In [43]:
a = tt.tensor([1,2,3])
b = tt.tensor([1,2,3])

In [44]:
a.add_(b)
print(a)

tensor([2, 4, 6])


In [45]:
a.sub_(b)


tensor([1, 2, 3])

In [46]:
#input like

a = tt.tensor([1,2,3],dtype=tt.float64)
b = tt.rand_like(a)
b

tensor([0.9751, 0.7911, 0.4274], dtype=torch.float64)

In [47]:
#finding posision of small element (agrmin) and of big position (argmax)

In [48]:
a 

tensor([1., 2., 3.], dtype=torch.float64)

In [49]:
tt.argmax(a) #3 in math of real world it is 3 

tensor(2)

In [50]:
tt.argmin(a)#0

tensor(0)

In [51]:
#variance of math
tt.var(a)

tensor(1., dtype=torch.float64)

In [52]:
tt.exp(a)

tensor([ 2.7183,  7.3891, 20.0855], dtype=torch.float64)

In [53]:
tt.log(a)

tensor([0.0000, 0.6931, 1.0986], dtype=torch.float64)

In [54]:
#round
a = tt.tensor([1.0,1.99,2.1,2.9])
print(a.round())#using math of python
print(tt.round(a))

tensor([1., 2., 2., 3.])
tensor([1., 2., 2., 3.])


In [55]:
#trignometry
#sin,cos,tan....
tt.sin(a)

tensor([0.8415, 0.9134, 0.8632, 0.2392])

In [56]:
tt.cos(a)

tensor([ 0.5403, -0.4070, -0.5048, -0.9710])

In [57]:
tt.tan(a)

tensor([ 1.5574, -2.2441, -1.7098, -0.2464])

In [58]:
#floor
a = tt.tensor([2.02222222222222222222,2.2222222222222,3])
a

tensor([2.0222, 2.2222, 3.0000])

In [59]:
tt.floor(a) #cuts down the deminal values and makes them 0

tensor([2., 2., 3.])

In [60]:
#high and advanced operation
#sigmoid
#softmax
#relu

In [61]:
a = tt.tensor([-2,4,6])
a

tensor([-2,  4,  6])

In [62]:
#relu 
tt.relu(a) #if negative value converts into 0

tensor([0, 4, 6])

In [63]:
#softmax
a = tt.tensor([1,2,3,4],dtype=tt.float32)
tt.softmax(a,dim=0)

tensor([0.0321, 0.0871, 0.2369, 0.6439])

In [64]:
#sigmoid
tt.sigmoid(a)


tensor([0.7311, 0.8808, 0.9526, 0.9820])

In [65]:
id(a)

1305768017536

In [66]:
id(b)

1305768012416

In [67]:
#id for finding id (location in the cpu)

finding device name and seeing is it CPU OR GPU

In [68]:
#finding device name
device = [("GPU") if tt.cuda.is_available() else ("CPU")]

device

['CPU']

In [69]:
print("device is:",tt.cuda.get_device_name(0) if device == "GPU" else "cpu")

device is: cpu


In [70]:
## finding minimum and maximum in tensor
tensor2 = tt.tensor([1,2,3])
print(tt.min(tensor2)) #finding minimum though torch
print(min(tensor2)) #finding minimum though main python

tensor(1)
tensor(1)


In [71]:
## finding maximum 
tensor2 = tt.tensor([1,2,3])
print(tt.max(tensor2)) #finding max though torch
print(max(tensor2)) #finding max though main python

tensor(3)
tensor(3)


## finding index number of any number in tensor


In [72]:
tensor2

tensor([1, 2, 3])

## Comparing in tensors

##### greater than
##### less than
##### equal to
##### equal to or less
##### equal to or great
##### not equal to

In [73]:
a = tt.tensor([1,2,3])
b = a.clone() + 5  #copy the a and also add 5 to each element of the b
print(a)
print(b)

tensor([1, 2, 3])
tensor([6, 7, 8])


In [74]:
print(a>b) #false in all elements  greater than

tensor([False, False, False])


In [75]:
a<b #true true true (in all elements) - less than

tensor([True, True, True])

In [76]:
a==b #a is equal to b which is false

tensor([False, False, False])

In [77]:
a!=b # a isn't equal to b that is true

tensor([True, True, True])

In [78]:
a>=b # a is greater than b or equal to b which is false

tensor([False, False, False])

In [79]:
a<=b # a is less than b or equal to b which is true

tensor([True, True, True])

# comparing with number


In [80]:
a = tt.tensor([1,2,3])
a

tensor([1, 2, 3])

In [81]:
a > 5 

tensor([False, False, False])

In [82]:
a < 5

tensor([True, True, True])

In [83]:
a == 5

tensor([False, False, False])

In [84]:
a != 2

tensor([ True, False,  True])

In [85]:
a >=5

tensor([False, False, False])

In [86]:
a <= 2

tensor([ True,  True, False])

## Other ways

In [87]:
#full function
number_in_tensor = 7
size = (2,3)
tt.full(size,number_in_tensor)


tensor([[7, 7, 7],
        [7, 7, 7]])

In [88]:
tt.eye(7) #making tensor of square whose one side is 7 and total of elements should be 7^2 that is 49  , it makes cross line between them 1 abd and all other is 0

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [89]:
#arrange
steps = 2
start1 = 1
end1 = 10 
#so it must be 1,3,5,7,9
tt.arange(start1,end1,steps)

tensor([1, 3, 5, 7, 9])

In [90]:
#linespace

tt.linspace(0,1,20) #evenly spaced values

tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])

In [91]:
#reshaping the tensor
# the best method is reshape
#lets do it!!!
a = tt.ones(100,1000)
a.shape 

torch.Size([100, 1000])

In [92]:
a = a.reshape(100000,1)


#Rule:the multiply of elements before in the shape must be equal to new product of elements in new shape

In [93]:
b = tt.randint(size=(10,10),high = 100,low = -1)
print(b)
b.shape

tensor([[83,  1, 63, 63, 43, 96, 47, 13, 29, 95],
        [17, 39, 31,  2, 21, 24, 34, 69, 81, 68],
        [84, 46, 56, 61, 56, 42, 28, -1, 77, 61],
        [51, 33, 50, 11, 84, 13, 77, 57, 52, 36],
        [16,  1, 27, 37, 81, 28, 39,  4,  6,  0],
        [95, 57, 89,  3, 59, 73, 66, 83, 40, 42],
        [ 9, 68, 98, 59, 31, 60, 46, 39, 17, 57],
        [10, 56, 49, 55,  0, 82, 12, 85,  0, 16],
        [70, 43, 89, 69, 64, 50, 42, 33, 45, 26],
        [18, 57, 26, 60, 79, 82,  2, 62, 57, 38]])


torch.Size([10, 10])

In [94]:
b = tt.flatten(b) #converts whole rows in one row
b.shape

torch.Size([100])

# Small Project

In [95]:
import time

In [99]:
print("device:",*device)
st = time.time()
matrix_a = tt.randint(size=(5000,7000),high = 540,low = -50)
print("matrix a : ", matrix_a)
matrix_b = tt.randint(size=(7000,5000),high=600,low = -999)
print("matrix b:",matrix_b)



device: CPU
matrix a :  tensor([[435, 409,  -9,  ..., 242,  57, 449],
        [299, 378, -18,  ..., 124, 353, 141],
        [234, 436, 143,  ...,  69, 253, 520],
        ...,
        [369, 528, 343,  ..., 134, 322, 115],
        [520, 216,  -8,  ..., 318, 411, 156],
        [201, 458, 533,  ..., 265, 312, 133]])
matrix b: tensor([[-559, -719, -841,  ..., -217, -647, -189],
        [  69, -158, -935,  ..., -461,  149,    3],
        [  41, -565,  207,  ...,  250, -566, -353],
        ...,
        [-559,   66,  558,  ..., -658,  316,   84],
        [-688, -602,  569,  ...,   15,  432,  130],
        [-412,  513, -217,  ..., -911,  156,   25]])


In [100]:
#checking time taken in cpu of matrix multipulcation of 1100x1000 and 1000x1100
st = time.time()
output = tt.matmul(matrix_a,matrix_b)

et = time.time()
print(output)

print("time taken:",et-st,'seconds')

tensor([[-328719217, -350837164, -337655085,  ..., -352682514, -339717258,
         -352515195],
        [-337194110, -344961699, -347850530,  ..., -342354328, -344733549,
         -344812010],
        [-323998312, -348952351, -353282211,  ..., -336862709, -349703448,
         -332864820],
        ...,
        [-329283817, -353466115, -352065049,  ..., -342064874, -351398964,
         -348507056],
        [-335903719, -350952771, -344013303,  ..., -346026242, -336920183,
         -356180799],
        [-339516366, -346054701, -354459923,  ..., -351671030, -351106207,
         -354053359]])
time taken: 163.35336422920227 seconds


# thanks for this course - Tabish showkat
